### ISSUE TITLE
please update in swift3.0

### ISSUE THREAD

**Issue by qiulang** [freak4pc/UIView-Positioning#14]
xcode can help fix it

**Comment by qiulang** [comment]
The only problem xcode can't fix is, in my opinion, better to use public extension UIView instead of extension UIView. Otherwise it can't be used in objective c codes

**Comment by freak4pc** [comment]
Sorry for not noticing earlier! Had some e-mail issues.
The master branch is now updated for Swift 3, as well as the Cocoapod (v1.5).
