### ISSUE TITLE
Any plans to implement functions for bounds?

### ISSUE THREAD

**Issue by lisbakke** [freak4pc/UIView-Positioning#6]

**Comment by freak4pc** [comment]
What would you like to see exactly? All methods for bounds instead of frame ?

**Comment by lisbakke** [comment]
Just adding methods for bounds. e.x.:
https://gist.github.com/lisbakke/bd050f5d477c998a6604

**Comment by freak4pc** [comment]
Seems reasonable. Only thing is I'm not sure exactly how would I name those. Maybe just boundsX, boundsY, boundsWidth, boundsHeight ?

**Comment by lisbakke** [comment]
Yeah, those names would do the trick.

**Comment by freak4pc** [comment]
Done! have fun.
