### ISSUE TITLE
Why leave out top and left? 

### ISSUE THREAD

**Issue by SeanDunford** [freak4pc/UIView-Positioning#7]
I understand that it would just be an alias of x and y but it seems odd to have 
x, y , bottom , right?

**Comment by freak4pc** [comment]
Doesn't seem like an issue to me , because as you said its just an alias. Will add this in the upcoming release though , for the heck of it :) cheers.

**Comment by SeanDunford** [comment]
<3

**Comment by freak4pc** [comment]
Done!
